include:
  - docker-compose.yml

services:
  app:
    build:
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./app
          target: /app
        - action: rebuild
          path: ./app/package.json
        - action: rebuild
          path: ./.env